# Generated by Django 4.1 on 2022-10-26 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='temperatures',
            new_name='temperature',
        ),
    ]
