# Generated by Django 4.1 on 2022-10-26 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sensors', '0002_rename_temperatures_sensor_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='onwer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
