# Generated by Django 4.1 on 2022-10-26 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_sensor_onwer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='onwer',
            new_name='owner',
        ),
    ]
