# Generated by Django 4.1 on 2022-11-06 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_rename_onwer_sensor_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='identify',
            field=models.IntegerField(default=0),
        ),
    ]
